name: klaviyo_flutter
description: Flutter plugin for Klaviyo integration. Provides push messaging
  and Klaviyo analytics services
version: 0.3.0
homepage: https://github.com/drybnikov/klaviyo_flutter

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  equatable: ^2.0.5
  firebase_messaging: ">=15.0.0 <18.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  collection: ^1.16.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rightbite.denisr
        pluginClass: KlaviyoFlutterPlugin
      ios:
        pluginClass: KlaviyoFlutterPlugin
